apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# namePrefix: dev-

helmCharts:
  - name: nginx
    repo: https://charts.bitnami.com/bitnami
    version: 15.5.2
    releaseName: nginx
    namespace: nginx
    valuesFile: values/nginx-values.yaml

  - name: redis
    repo: https://charts.bitnami.com/bitnami
    version: 19.5.2
    releaseName: redis
    namespace: redis
    valuesFile: values/redis-values.yaml

  - name: fdl
    repo: https://asoltes.github.io/fdl-app-helm-charts/
    version: 0.1.1
    releaseName: fdl
    namespace: fdl
    valuesFile: values/fdl-values.yaml