apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: nginx
    repo: https://charts.bitnami.com/bitnami
    version: 15.5.2
    releaseName: nginx
    namespace: nginx
    valuesFile: nginx-values.yaml

  - name: redis
    repo: https://github.com/bitnami/charts.git
    # path: bitnami/redis
    version: 19.5.2
    releaseName: redis
    namespace: redis
    valuesFile: redis-values.yaml

resources:
  - namespace-nginx.yaml
  - namespace-redis.yaml
