apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: fdl-app
    repo: https://asoltes.github.io/fdl-app-helm-charts/
    version: 15.5.2
    releaseName: fdl-app
    namespace: fdl-app
    valuesFile: nginx-values.yaml

  - name: redis
    repo: https://charts.bitnami.com/bitnami
    version: 19.5.2
    releaseName: redis
    namespace: redis
    valuesFile: redis-values.yaml

resources:
  - namespace-nginx.yaml
  - namespace-redis.yaml
