apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: fdl
    repo: https://github.com/asoltes/fdl-app-helm-charts.git
    version: HEAD
    releaseName: fdl
    namespace: fdl
    valuesFile: values.yaml

resources:
  - namespace.yaml

namespace: fdl
